### ISSUE TITLE
generated clocks and other sdc concerns

### ISSUE THREAD

**Issue by kareefardi** [efabless/caravel#116]
- a generated clock has a list of pins driven by the clock. if a pin belongs to multiple generated clocks they override each other without `-add` flag. which was the case with `csclk_fast` and `serial_clock_wb` in housekeeping sdc and other blocks/generated cocks
- some generated clocks have no loads which questions the value of defining such clocks
- generated clocks are referring to instance names in the synthesized netlist which changes in case of re-implementation. an approach such as the one here https://github.com/kareefardi/caravel/blob/openlane_config_updates/sdc/housekeeping.sdc can possibly eliminate such an issue
- generated clocks in housekeeping are getting multiplied ? 
- input and output delays are bound to a clock. the question is which clock each port should be bound to? fastest clock?
- output loads are fixed in housekeeping sdc and (possibly others). they are not varying according to projected connectivity for the output port based on the floorplan of caravel.

**Comment by azwefabless** [comment]
Each issue was broken out and solved separately as independent problems. The final issue remains as a deferred issue for future flow development.

output loads are fixed in housekeeping sdc and (possibly others). they are not varying according to projected connectivity for the output port based on the floorplan of caravel.
