### ISSUE TITLE
replace OpenRAM with DFFRAM

### ISSUE THREAD

**Issue by jeffdi** [efabless/caravel#150]

**Comment by RTimothyEdwards** [comment]
Specifically:  Replace the 2k x 8 SRAM from OpenRAM with a 2nd 1k x 8 DFFRAM.  Since the DFFRAM is not dual-port, remove the exported SRAM signals from the management SoC and the connecting inputs to the housekeeping block.  Most of the work is to be done in the caravel_mgmt_soc_litex repository.  In caravel, only the housekeeping and management SoC ports need to be removed.
