### ISSUE TITLE
fix for Antenna issue

### ISSUE THREAD

**Issue by jeffdi** [efabless/caravel#351]

**Comment by marwaneltoukhy** [comment]
Full log for antenna violations on caravel:
[caravel_antenna_vios.txt](https://github.com/efabless/caravel/files/9911591/calculated_vios.txt)
Full log for antenna violations on caravan:
[caravan_antenna_vios.txt](https://github.com/efabless/caravel/files/9911597/calculated_vios.txt)

DFFRAM violations were fixed in [PR 111](https://github.com/efabless/caravel_mgmt_soc_litex/pull/111)
top level caravel and caravan violations greater than 10x fixed in #361
