### ISSUE TITLE
max transition issue with user project signals

### ISSUE THREAD

**Issue by jeffdi** [efabless/caravel#352]

**Comment by mo-hosni** [comment]
- Issue:
This was related to mgmt_protect. Input user project signals were marked as "don't touch" so they were not buffered before the NAND gates inside mgmt_protect as they could be floating. The placer placed the cells in mgmt_protect very close to output ports and hence very far from the input ports. So, input user project signals had long wires (>1mm) without buffering and this caused the max transition violation.

- Fix: 
mgmt_protect was rehardened using routablity-driven placement rather than a time-driven one. Target placement density was also calibrated. That resulted in a better placement with the NAND gates placed very close to the input ports; hence, the max transition violation was fixed.

- Pull request:
#356
