### ISSUE TITLE
vdda and vssa are not connected to anything in the chip core

### ISSUE THREAD

**Issue by mo-hosni** [efabless/caravel#383]
Does that mean that the chip has only 6 power-supplies not 7?

**Comment by RTimothyEdwards** [comment]
Just because it's not connected to anything in the core doesn't mean it's not connected to something in the padframe.  The padframe needs to have the vdda/vssa busses powered up for the analog portion of the GPIO.  The expectation is that future versions of the chip will use the vdda supply to power analog components like LDOs or ADCs.

**Comment by RTimothyEdwards** [comment]
I am going to close this because as far as I know it is not an issue, just an observation.  Which should have been taken up in a slack channel, not the issue tracker.
